trigger:
  - none

pool: prod-pool

stages:
  - stage: FirstStage
    displayName: TerraformInstall

    jobs:
      - job: InstallTerraform
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

  - stage: SecondStage
    displayName: TerraformInit
    jobs:
      - job: Init
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: 'D:\Agent\vsts-agent-win-x64-4.274.1\_work'
              backendServiceArm: 'prod-sc'
              backendAzureRmStorageAccountName: 'backendstg921'
              backendAzureRmContainerName: 'backendcnt921'
              backendAzureRmKey: 'prod.tfstate'
    
          
            