trigger:
  - none

pool: prod-pool

stages:
  - stage: FirstStage
    displayName: TerraformInstall

    jobs:
      - job: InstallTerraform
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

  - stage: SecondStage
    displayName: TerraformInit
    jobs:
      - job: Init
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Terraform'
              backendServiceArm: 'sid-sc'
              backendAzureRmStorageAccountName: 'sidstg1'
              backendAzureRmContainerName: 'sidcnt1'
              backendAzureRmKey: 'prac.tfstate'

  - stage: ThirdStage
    displayName: TerraformPlan
    jobs:
      - job: Plan
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Terraform'
              commandOptions: '-reconfigure'
              backendServiceArm: 'sid-sc'
              backendAzureRmStorageAccountName: 'sidstg1'
              backendAzureRmContainerName: 'sidcnt1'
              backendAzureRmKey: 'prac.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Terraform'
              commandOptions: '-var-file="environment "$(System.DefaultWorkingDirectory)\Terraform\dev\terraform.tfvars"'
              environmentServiceNameAzureRM: 'sid-sc'
          
            